name: Pygmeeweb
markdown: redcarpet
pygments: true
relative_permalinks: false

recent_posts: 5      # Posts on home page

exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile

url: http://pygmeeweb.com
disqus_shortname: pygmeeweb