name: Pygmeeweb
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
relative_permalinks: false

recent_posts: 50      # Posts on home page

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

url: http://pygmeeweb.com
disqus_shortname: pygmeeweb